import Head from 'next/head'
import Link from 'next/link'
import { AppShell, Navbar, Header } from '@mantine/core';
import styles from '../../styles/Home.module.css'
import React from 'react'




export default function Home( { genres } ) {

  return (

    <AppShell
      padding="md"
      // navbar={<Navbar width={{ base: 300 }} height={500} padding="xs">{/* Navbar content */}</Navbar>}
      header={<Header height={60} padding="sm">{/* Header content */}</Header>}
      styles={(theme) => ({
        main: { backgroundColor: theme.colorScheme === 'dark' ? theme.colors.dark[8] : theme.colors.gray[0] },
      })}>
      <div className={styles.container}>
        <Head>
          <title>Music App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Genre List</h1>
          <ul>
            {genres.map( genre => 
              <li key={genre}>
                <Link href={`/genres/${genre}`}>
                  <a>{genre}</a>
                </Link>
              </li>)
            }
          </ul>
        </main>
      </div>
    </AppShell>
  )
}

export async function getStaticProps() {
  
  const data = await fetch("https://api.spotify.com/v1/recommendations/available-genre-seeds",
  {  
    headers: {
    Authorization: `Bearer ${process.env.NEXT_PUBLIC_SPOTIFY_OAUTH_TOKEN}`
    }
  }).then(response => response.json());

  return {
    props: {
      genres: data.genres
    }
  }
}