import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import React from 'react'
import SearchBar from '../components/searchbar'

export default function Home( { genres } ) {
  console.log(genres);







  return (
    <div className={styles.container}>
      <Head>
        <title>Music App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Music Recommender
        </h1>
        Recommended Artists
        <h2>Genre List</h2>

        <SearchBar/>

        <ul>
          {genres.map( genre => 
            <li key={genre}>
              <Link href={`/${genre}`}>
                <a>{genre}</a>
              </Link>
            </li>)
          }
        </ul>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  
  const data = await fetch("https://api.spotify.com/v1/recommendations/available-genre-seeds",
  {  
    headers: {
    Authorization: `Bearer ${process.env.SPOTIFY_OAUTH_TOKEN}`
    }
  }).then(response => response.json());

  return {
    props: {
      genres: data.genres
    }
  }
}