import Head from 'next/head'
import { Group, Center } from '@mantine/core';
import styles from '../styles/Home.module.css'
import { React, useState } from 'react'
import Header from '../components/header';

export default function Home() {

  return (<>

    <Head>
      <title>Songbrrd</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />

    <Center style={{ marginTop: 100}}>
      <Group position='center' direction='column' spacing="xl">
        <h1 className={styles.title}>Welcome to Songbrrd</h1>
        <h2 >A social network for music lovers</h2>
      </Group>
    </Center>
  </>
  )
}